isPublic: false
name: Frontend
scope:
  - 'sections.a27ce8af-199a-455d-8d8e-dbeb7b3f117b:read' # About
  - 'entrytypes.52519e78-2e53-47c5-aa84-c2345d520393:read' # About
  - 'sections.3400f929-2ff0-47da-8c15-40bce8b6cebf:read' # Customize Orbits
  - 'entrytypes.2f6b435a-5a6c-4f32-b8b5-4aae301d1738:read' # Customize Orbits
  - 'sections.907d717b-d9ff-4449-abbf-7c7f5823851b:read' # Guided Experiences
  - 'entrytypes.7242b43a-de73-46de-b5c2-234ba48a8a57:read' # Default
  - 'sections.f1df2c63-97e5-49f0-8f4d-1e704d4945ac:read' # Landing
  - 'entrytypes.3cbe4fda-03b6-4891-b0ac-892db5b17bb8:read' # Landing
  - 'sections.59e08766-55d3-4cb0-8b02-b406b1ea45d8:read' # Solar system Elements
  - 'entrytypes.ec809547-cd72-4016-92f4-e72a89d6620c:read' # Default
  - 'volumes.7754bae8-c6eb-4fbe-882b-236621e35f2d:read' # Canto DAM
